version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env.dev
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend