const skillCategories = {
    IT: [
        "HTML",
        "CSS",
        "Javascript",
        "Java",
        "C",
        "C++",
        "React",
        "Django",
        "Node.js",
        "Express.js",
        "DevOps",
        "Cybersecurity",
        "Machine Learning",
        "Cloud Computing",
        "Python",
        "MongoDB",
        "SQL",
        "Docker",
    ],
    Marketing: [
        "SEO",
        "Social Media Marketing",
        "Content Writing",
        "Google Ads",
        "Email Marketing",
        "Market Research",
        "Copywriting",
        "Facebook Ads",
        "Brand Management",
        "PPC Advertising",
    ],
    Healthcare: [
        "Nursing",
        "Pharmacy",
        "Medical Research",
        "Surgery",
        "Patient Care",
        "Public Health",
        "Physical Therapy",
        "Radiology",
        "Emergency Medicine",
        "Clinical Trials",
    ],
    Engineering: [
        "Civil Engineering",
        "Mechanical Engineering",
        "Electrical Engineering",
        "CAD Design",
        "Structural Analysis",
        "Thermodynamics",
        "Robotics",
        "Project Management",
        "Quality Assurance",
        "Manufacturing Processes",
    ],
    Architecture: [
        "Building Design",
        "Urban Planning",
        "Landscape Architecture",
        "AutoCAD",
        "3D Modeling",
        "Interior Design",
        "Sustainable Architecture",
        "SketchUp",
        "BIM (Building Information Modeling)",
        "Structural Engineering",
    ],
    Finance: [
        "Financial Analysis",
        "Accounting",
        "Investment Management",
        "Risk Assessment",
        "Cryptocurrency",
        "Auditing",
        "Taxation",
        "Budgeting",
        "Stock Market Analysis",
        "Financial Forecasting",
    ],
    Education: [
        "Curriculum Development",
        "E-Learning",
        "Special Education",
        "Public Speaking",
        "Classroom Management",
        "Educational Technology",
        "Lesson Planning",
        "Tutoring",
        "Research & Teaching",
        "Assessment & Evaluation",
    ],
    HumanResources: [
        "Recruiting",
        "Employee Training",
        "HR Analytics",
        "Compensation & Benefits",
        "Workplace Diversity",
        "Conflict Resolution",
        "Performance Management",
        "Payroll Management",
        "Labor Law Compliance",
        "Organizational Development",
    ],
    Legal: [
        "Corporate Law",
        "Intellectual Property",
        "Contract Negotiation",
        "Legal Writing",
        "Litigation",
        "Employment Law",
        "Compliance",
        "Criminal Law",
        "Real Estate Law",
        "Mediation & Arbitration",
    ],
    SoftSkills: [
        "Communication",
        "Problem-Solving",
        "Time Management",
        "Leadership",
        "Adaptability",
        "Emotional Intelligence",
        "Creativity",
        "Collaboration",
        "Critical Thinking",
        "Resilience",
    ],
};

export default skillCategories;
