"""
Utilities for embedding extraction and processing.

ARCHITECTURE NOTE:
    This module is a pure compute layer — zero DB access.
    All data (skill docs, job title docs, location docs) must be
    pre-fetched by the caller (Node.js) and passed in as plain dicts.

    Backfill candidates (DB entries with null embeddings that were
    re-generated by the model) are RETURNED to the caller so Node.js
    can write them back. Python never writes to DB.

Caller contract:
    - skill_docs:     list of { name, embedding | null, _id }
    - job_title_doc:  { title, embedding | null, _id } | None
    - location_doc:   { name,  embedding | null, _id } | None
"""

import json
import logging
from typing import Optional, cast
import torch
from models.embeddings import embedding_model
from utils.tensor_utils import stack_embeddings, safe_mean_embedding
from utils.sanitization_utils import strip_html

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# Skills
# ──────────────────────────────────────────────────────────────────────────────


def extract_skills_embeddings(
    skills: list[dict],
    skill_docs: list[dict],
) -> tuple[Optional[torch.Tensor], list[str], list[torch.Tensor]]:
    """
    Extract mean skill embedding from pre-fetched skill documents.

    Node pre-fetches the skill docs (with embeddings) and passes them in.
    This function uses cached vectors where available and falls back to the
    model only for skills with null embeddings or not found in the DB.

    Args:
        skills:     List of skill dicts from the resume, each with a 'name' field.
        skill_docs: Pre-fetched skill documents from Node (may include embedding
                    vector or null). Each doc: { _id, name, embedding | null, ... }

    Returns:
        Tuple of:
          - mean skill embedding tensor, or None if no embeddings could be produced
          - list of skill document IDs that need backfill (existed in DB but had
            null embeddings — caller should write the new vectors back)
          - list of per-skill tensors aligned to the backfill ID list, so the
            caller can store the correct vector per skill rather than the mean
    """
    # filter(None, ...) + the truthy check together guarantee every
    # surviving entry is a non-empty str, but mypy can't infer that through
    # a list comprehension over dict.get(). cast() documents the invariant
    # we just enforced rather than weakening it with type: ignore.
    skill_names: list[str] = [cast(str, s.get("name")) for s in skills if s.get("name")]
    if not skill_names:
        return None, [], []

    # Build a lookup from the pre-fetched docs
    skill_map = {doc.get("name"): doc for doc in skill_docs}

    all_embeddings: list[torch.Tensor] = []
    missing_skills: list[str] = []  # need model fallback
    needs_backfill: list[str] = []  # have a DB _id but embedding was null

    for skill_name in skill_names:
        doc = skill_map.get(skill_name)

        if doc and doc.get("embedding"):
            all_embeddings.append(torch.tensor(doc["embedding"]))
        elif doc and not doc.get("embedding"):
            # In DB but null — regenerate and flag for backfill
            logger.warning(
                f"Skill '{skill_name}' has null embedding — falling back to model"
            )
            missing_skills.append(skill_name)
            needs_backfill.append(str(doc["_id"]))
        else:
            # Not in DB at all — generate but nothing to backfill
            logger.warning(
                f"Skill '{skill_name}' not in pre-fetched docs — falling back to model"
            )
            missing_skills.append(skill_name)

    backfill_embeddings: list[torch.Tensor] = []

    if missing_skills:
        fallback = embedding_model.encode_batch(missing_skills)
        if fallback is not None:
            if isinstance(fallback, torch.Tensor):
                per_skill = (
                    [fallback.detach().cpu()]
                    if fallback.dim() == 1
                    else [e.detach().cpu() for e in fallback]
                )
            else:
                per_skill = [e.detach().cpu() for e in fallback]

            all_embeddings.extend(per_skill)

            # missing_skills ordering: null-embedding skills (those with a DB id
            # to backfill) are appended before not-in-DB skills, so the first
            # len(needs_backfill) fallback tensors correspond to backfill entries.
            backfill_embeddings = per_skill[: len(needs_backfill)]

    if not all_embeddings:
        return None, needs_backfill, backfill_embeddings

    stacked = stack_embeddings(all_embeddings)
    return safe_mean_embedding(stacked), needs_backfill, backfill_embeddings


# ──────────────────────────────────────────────────────────────────────────────
# Job title
# ──────────────────────────────────────────────────────────────────────────────


def extract_job_title_embedding(
    job_title: str,
    job_title_doc: Optional[dict],
) -> tuple[Optional[torch.Tensor], Optional[str]]:
    """
    Extract job title embedding from a pre-fetched document.

    Args:
        job_title:     Raw job title string (used as model fallback text).
        job_title_doc: Pre-fetched document from Node:
                       { _id, title, embedding | null } or None if not in DB.

    Returns:
        Tuple of:
          - embedding tensor, or None on failure
          - document ID to backfill, or None (no backfill needed)
    """
    if not job_title:
        return None, None

    needs_backfill: Optional[str] = None

    if job_title_doc and job_title_doc.get("embedding"):
        return torch.tensor(job_title_doc["embedding"]), None

    if job_title_doc and not job_title_doc.get("embedding"):
        logger.warning(
            f"Job title '{job_title}' has null embedding — falling back to model"
        )
        needs_backfill = str(job_title_doc["_id"])
    else:
        logger.warning(
            f"Job title '{job_title}' not in pre-fetched doc — falling back to model"
        )

    embedding = embedding_model.encode(job_title)
    if embedding is None:
        return None, needs_backfill

    return embedding.detach().cpu(), needs_backfill


# ──────────────────────────────────────────────────────────────────────────────
# Location
# ──────────────────────────────────────────────────────────────────────────────


def extract_location_embedding(
    location_name: str,
    location_doc: Optional[dict],
) -> tuple[Optional[torch.Tensor], Optional[str]]:
    """
    Extract location embedding from a pre-fetched document.

    Args:
        location_name: Raw location string (used as model fallback text).
        location_doc:  Pre-fetched document from Node:
                       { _id, name, embedding | null } or None if not in DB.

    Returns:
        Tuple of:
          - embedding tensor, or None on failure
          - document ID to backfill, or None (no backfill needed)
    """
    if not location_name:
        return None, None

    needs_backfill: Optional[str] = None

    if location_doc and location_doc.get("embedding"):
        return torch.tensor(location_doc["embedding"]), None

    if location_doc and not location_doc.get("embedding"):
        logger.warning(
            f"Location '{location_name}' has null embedding — falling back to model"
        )
        needs_backfill = str(location_doc["_id"])
    else:
        logger.warning(
            f"Location '{location_name}' not in pre-fetched doc — falling back to model"
        )

    embedding = embedding_model.encode(location_name)
    if embedding is None:
        return None, needs_backfill

    return embedding.detach().cpu(), needs_backfill


# ──────────────────────────────────────────────────────────────────────────────
# Work experience
# ──────────────────────────────────────────────────────────────────────────────


def extract_work_experience_embeddings(
    work_experiences: list[dict],
    job_title_docs: list[dict],
) -> Optional[torch.Tensor]:
    """
    Extract mean work experience embedding from pre-fetched job title documents.

    For each work experience entry, uses the cached embedding from the matching
    job title document. Falls back to model-encoding (title + responsibilities)
    only for titles not present or with null embeddings in the pre-fetched docs.

    Args:
        work_experiences: List of work experience dicts, each with 'jobTitle'
                          and optionally 'responsibilities'.
        job_title_docs:   Pre-fetched job title documents from Node, each with
                          { _id, title | name, embedding | null }.

    Returns:
        Mean work experience embedding tensor, or None.
    """
    if not work_experiences:
        return None

    # Build lookup — docs may use 'title' or 'name' depending on collection
    title_map = {(doc.get("title") or doc.get("name")): doc for doc in job_title_docs}

    embeddings: list[torch.Tensor] = []
    fallback_texts: list[str] = []

    for exp in work_experiences:
        job_title = exp.get("jobTitle", "")
        if not job_title:
            continue

        doc = title_map.get(job_title)

        if doc and doc.get("embedding"):
            embeddings.append(torch.tensor(doc["embedding"]))
        else:
            # Build fallback: title + responsibilities concatenated
            responsibilities = exp.get("responsibilities", [])
            if responsibilities:
                resp_strings = [
                    json.dumps(r) if isinstance(r, dict) else str(r)
                    for r in responsibilities
                ]
                fallback_texts.append(f"{job_title}: {', '.join(resp_strings)}")
            else:
                fallback_texts.append(job_title)

            reason = (
                "null embedding"
                if (doc and not doc.get("embedding"))
                else "not in pre-fetched docs"
            )
            logger.warning(f"Job title '{job_title}' {reason} — falling back to model")

    if fallback_texts:
        fallback_embeddings = embedding_model.encode_batch(fallback_texts)
        if fallback_embeddings is not None:
            if isinstance(fallback_embeddings, torch.Tensor):
                if fallback_embeddings.dim() == 1:
                    embeddings.append(fallback_embeddings.detach().cpu())
                else:
                    embeddings.extend(e.detach().cpu() for e in fallback_embeddings)
            else:
                embeddings.extend(e.detach().cpu() for e in fallback_embeddings)

    if not embeddings:
        return None

    stacked = stack_embeddings(embeddings)
    return safe_mean_embedding(stacked)


# ──────────────────────────────────────────────────────────────────────────────
# These three never touched the DB — no changes needed beyond keeping them here
# ──────────────────────────────────────────────────────────────────────────────


def extract_certification_embeddings(
    certifications: list[dict],
) -> Optional[torch.Tensor]:
    """
    Extract and compute mean embedding for certifications.
    Pure model inference — no DB access, no pre-fetched docs needed.

    Args:
        certifications: List of certification dicts with 'name' field.

    Returns:
        Mean certification embedding or None.
    """
    certification_names: list[str] = [
        cast(str, c.get("name")) for c in certifications if c.get("name")
    ]
    if not certification_names:
        return None

    embeddings = embedding_model.encode_batch(certification_names)
    return safe_mean_embedding(embeddings)


def extract_requirement_embeddings(requirements) -> Optional[torch.Tensor]:
    """
    Extract and compute mean embedding for job requirements.
    Supports both structured schema (dict) and legacy schema (list of strings).
    Pure model inference — no DB access.

    Args:
        requirements: dict (new schema) or list[str] (old schema).

    Returns:
        Mean requirements embedding or None.
    """
    if isinstance(requirements, dict):
        description = requirements.get("description")
        extracted = [strip_html(description)] if description else []

        if isinstance(requirements.get("education"), str):
            extracted.append(requirements["education"])
        if isinstance(requirements.get("yearsOfExperience"), (int, float)):
            extracted.append(
                f"Years of Experience: {requirements['yearsOfExperience']}"
            )
        if isinstance(requirements.get("certifications"), list):
            extracted.extend(
                c for c in requirements["certifications"] if isinstance(c, str)
            )

        if extracted:
            embeddings = embedding_model.encode_batch(extracted)
            return safe_mean_embedding(embeddings)

    elif isinstance(requirements, list) and all(
        isinstance(r, str) for r in requirements
    ):
        embeddings = embedding_model.encode_batch(requirements)
        return safe_mean_embedding(embeddings)

    return None


def extract_experience_level_embedding(experience_level: str) -> Optional[torch.Tensor]:
    """
    Extract embedding for an experience level string.
    Pure model inference — no DB access.

    Args:
        experience_level: e.g. "Intern", "Mid-Level", "Senior".

    Returns:
        Embedding tensor or None.
    """
    if not experience_level:
        return None

    embedding = embedding_model.encode(experience_level)
    if embedding is None:
        return None

    return embedding.detach().cpu()
